name: Trigger Submodule Workflow

on:
  workflow_dispatch:

jobs:
  trigger-submodule-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Original Workflow
        env:
          REPO_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token $REPO_TOKEN" \
          https://api.github.com/repos/cazelabs/ci-cd-github/dispatches \
          -d '{"event_type": "submodule_action"}'
