name: Sync Submodule Versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync_submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Initialize and update submodule
      run: |
        git submodule init
        git submodule update --remote --merge

    - name: Check for submodule updates
      run: |
        git submodule status
        git fetch
        git submodule update --remote

    - name: Commit submodule update (if any)
      run: |
        git add https://github.com/automate-1/exit-2.git
        git commit -m "Updated submodule to latest version"
        git push origin main
      # Only commit if there were changes to the submodule
      if: success() && github.event_name == 'push'


