name: Trigger Manage Submodules Workflow

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the "Manage Submodules" workflow in the original repository
        env:
          REPO_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token $REPO_TOKEN" \
          https://api.github.com/repos/cazelabs/ci-cd-github/dispatches \
          -d '{
                "event_type": "submodule_action",
                "client_payload": {
                  "repoPath": "/path/to/repo",
                  "submoduleUrl": "https://github.com/example/submodule",
                  "submoduleCommit": "commit_hash",
                  "action": "1",
                  "submodulePath": "path/to/submodule"
                }
              }'
